<a href="https://colab.research.google.com/github/Yankee1231/Control_Engineering/blob/main/Python_review5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 3x2 형태의 1 행렬 선언
# Input으로 Tuple을 받는 것에 주의!
import numpy as np
one_matrix = np.ones((3,2))
print(one_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# 3x2 형태의 0행렬 선언
zero_matrix = np.zeros((3,2))
print(zero_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
# 3x3 형태의 단위행렬 선언
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 리스트를 이용한 행렬 선언
data_int = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(data_int)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Matrix 형태 출력
print(data_int.shape)

(3, 3)


In [8]:
# 원소의 데이터형 출력
print(data_int.dtype)

int64


In [9]:
# 데이터형 변
data_float = data_int.astype(np.float64)
print(data_float)
print(data_float.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


In [10]:
# 요소별 곱셈
print(data_int * data_int)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [11]:
# 상수 덧셈
print(data_int * 3)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [12]:
# 상수 나눗셈
print(data_int / 3)

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [13]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 0, -1], [1, 1, 0]])
print(x)
print(y)
print(y.T)

[[1 2 3]
 [4 5 6]]
[[ 1  0 -1]
 [ 1  1  0]]
[[ 1  1]
 [ 0  1]
 [-1  0]]


In [14]:
# 행렬연산 행렬곱
print(x)
print(y)
print(y.T)

[[1 2 3]
 [4 5 6]]
[[ 1  0 -1]
 [ 1  1  0]]
[[ 1  1]
 [ 0  1]
 [-1  0]]


In [17]:
print(np.dot(x,y.T))

[[-2  3]
 [-2  9]]


In [19]:
# 연속 정수로 array 생성
data_range = np.arange(10)
print(data_range)

[0 1 2 3 4 5 6 7 8 9]
